version: '3.8'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile

        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/public

        depends_on: 
            - mysql
            - php

    mysql:
        image: mysql:8.0
        ports:
            - 3307:3307
        environment:
            MYSQL_DATABASE: testing 
            MYSQL_USER: sam 
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret

        volumes:
            - ./mysql:/var/lib/mysql

    php:
        image: php:8.0-fpm

        volumes:
            - ./src:/var/www/html/public

    composer:
        build:
            context: .
            dockerfile: composer.dockerfile

        volumes:
            - ./src:/var/www/html/public

        working_dir: /var/www/html/public

    npm: 
        image:  node:current-alpine
        volumes: 
            - ./src:/var/www/html/public
        entrypoint: ["npm"]
        working_dir: /var/www/html/public

